<script lang="ts">
	import { onDestroy } from 'svelte';

	export let previewUrl: string | null = null;
	export let width: number | null = null;
	export let height: number | null = null;
	export let name = 'Image upload';
	export let alt = 'Attachment generated by the assistant';

	$: aspectRatioStyle =
		width && height ? `aspect-ratio: ${width} / ${height}; max-width: min(95%, 700px);` : '';

	onDestroy(() => {
		if (previewUrl) {
			URL.revokeObjectURL(previewUrl);
		}
	});
</script>

{#if previewUrl}
	<div class="w-full leading-6">
		<div class="relative m-auto overflow-hidden rounded-xl" style={aspectRatioStyle}>
			<img class="block max-w-[min(95%,700px)]" src={previewUrl} {alt} />
		</div>
	</div>
{:else}
	<div
		class="flex items-center gap-3 rounded-lg border border-gray-200 bg-gray-50 px-4 py-3 text-gray-700"
	>
		<div>
			<div class="text-sm font-semibold">{name}</div>
			<div class="text-xs text-gray-500">Image upload pending</div>
		</div>
	</div>
{/if}
