name: Bug Report
description: File a bug report if you're seeing something that doesn't look right.
title: "[Bug]: "
labels: ["bug", "triage"]
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please complete all questions and provide a descriptive title, e.g. *Assistant files are missing after creating an assistant*
  - type: markdown
    attributes:
      value: "## Basic Information"
  - type: dropdown
    id: problem-area
    attributes:
      label: Which area are you seeing an issue with?
      options:
        - Assistants
        - Canvas Integration
        - Data & Sharing (Activity Summaries, Anonymous Sessions, Thread Exports)
        - Files
        - Groups
        - Login & Authentication
        - Models & Tools (File Search, Web Search, Code Interpreter, MCP)
        - Threads, Messages & Output
        - User Interface
        - Voice Mode
        - Something else not on this list
    validations:
      required: true
  - type: dropdown
    id: problem-type
    attributes:
      label: What type of issue are you reporting?
      options:
        - Incorrect/Unexpected Behavior
        - Application Crash
        - Application Slow/Unresponsive
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Description
        Please describe the issue and what steps we can take to reproduce it.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        Please include:

        - A clear description of the problem
        - A step-by-step set of instructions to reproduce the problem (if possible)
        - What results you expected
        - What results you actually saw
      placeholder: |
        Tell us what you see and how to reproduce it!
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Attachments"
  - type: textarea
    id: attachments
    attributes:
      label: Relevant files
      description: Please provide any relevant files or screenshots that might help demonstrate the problem. Use the Attach files button to add files, or paste screenshots here.
