name: Feature Request
description: File a feature request if you'd like to suggest an idea for this project.
title: "[Suggestion]: "
labels: ["feature", "triage"]
type: "Feature"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

        Please complete all questions and provide a descriptive title, e.g. *Assistant names should accept multi-line input*
  - type: markdown
    attributes:
      value: "## Basic Information"
  - type: dropdown
    id: problem-area
    attributes:
      label: Which area are you seeing an issue with?
      options:
        - Assistants
        - Canvas Integration
        - Data & Sharing (Activity Summaries, Anonymous Sessions, Thread Exports)
        - Files
        - Groups
        - Login & Authentication
        - Models & Tools (File Search, Web Search, Code Interpreter, MCP)
        - Threads, Messages & Output
        - User Interface
        - Voice Mode
        - Something else not on this list
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Description
        Please describe the issue and what steps we can take to reproduce it.
  - type: textarea
    id: description
    attributes:
      label: What's your suggestion?
      description: |
        Please include:

        - A clear description of the problem
        - A step-by-step set of instructions to reproduce the problem (if possible)
        - The solution you'd like to see
        - Alternative solutions or features you've considered

      placeholder: |
        Ex. It would be great if [...] because currently [...]
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Attachments"
  - type: textarea
    id: attachments
    attributes:
      label: Relevant files
      description: Please provide any relevant files or screenshots that might help demonstrate the problem. Use the Attach files button to add files, or paste screenshots here.
