"""Add API Key name

Revision ID: 0a9e2ba4455c
Revises: 29bf10fa9462
Create Date: 2024-11-21 21:43:46.924563

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a9e2ba4455c"
down_revision: Union[str, None] = "29bf10fa9462"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_keys", sa.Column("name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_keys", "name")
    # ### end Alembic commands ###
