"""Add Responses API Schema

Revision ID: 1dc9f1a10c8d
Revises: a805223f9983
Create Date: 2025-08-02 22:20:46.301568

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1dc9f1a10c8d"
down_revision: Union[str, None] = "a805223f9983"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                "INCOMPLETE",
                name="runstatus",
            ),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("incomplete_reason", sa.String(), nullable=True),
        sa.Column("thread_id", sa.Integer(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("completed", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.String(), nullable=True),
        sa.Column(
            "message_status",
            sa.Enum(
                "IN_PROGRESS",
                "COMPLETED",
                "INCOMPLETE",
                "PENDING",
                name="messagestatus",
            ),
            nullable=False,
        ),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("USER", "SYSTEM", "ASSISTANT", "DEVELOPER", name="messagerole"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("completed", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tool_call_id", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("CODE_INTERPRETER", "FILE_SEARCH", name="toolcalltype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "IN_PROGRESS",
                "SEARCHING",
                "INTERPRETING",
                "COMPLETED",
                "INCOMPLETE",
                "FAILED",
                name="toolcallstatus",
            ),
            nullable=False,
        ),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("completed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("queries", sa.String(), nullable=True),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("container_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "code_interpreter_call_outputs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tool_call_id", sa.Integer(), nullable=False),
        sa.Column(
            "output_type",
            sa.Enum("LOGS", "IMAGE", name="codeinterpreteroutputtype"),
            nullable=False,
        ),
        sa.Column("logs", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id"], ["tool_calls.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file_search_call_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attributes", sa.String(), nullable=True),
        sa.Column("file_id", sa.String(), nullable=True),
        sa.Column("file_object_id", sa.Integer(), nullable=True),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("tool_call_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["file_object_id"], ["files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["tool_call_id"], ["tool_calls.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "message_attachments_code_interpreter",
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
    )
    op.create_index(
        "message_attachments_code_interpreter_idx",
        "message_attachments_code_interpreter",
        ["message_id", "file_id"],
        unique=True,
    )
    op.create_table(
        "message_attachments_file_search",
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
    )
    op.create_index(
        "message_attachments_file_search_idx",
        "message_attachments_file_search",
        ["message_id", "file_id"],
        unique=True,
    )
    op.create_table(
        "message_parts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "INPUT_TEXT",
                "INPUT_IMAGE",
                "OUTPUT_TEXT",
                "REFUSAL",
                name="messageparttype",
            ),
            nullable=False,
        ),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("input_image_file_id", sa.String(), nullable=True),
        sa.Column("input_image_file_object_id", sa.Integer(), nullable=True),
        sa.Column("refusal", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["input_image_file_object_id"], ["files.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "annotations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "FILE_PATH",
                "URL_CITATION",
                "FILE_CITATION",
                "CONTAINER_FILE_CITATION",
                name="annotationtype",
            ),
            nullable=False,
        ),
        sa.Column("message_part_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.String(), nullable=True),
        sa.Column("file_object_id", sa.Integer(), nullable=True),
        sa.Column("container_id", sa.String(), nullable=True),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("index", sa.Integer(), nullable=True),
        sa.Column("start_index", sa.Integer(), nullable=True),
        sa.Column("end_index", sa.Integer(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["file_object_id"], ["files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["message_part_id"], ["message_parts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("annotations")
    op.drop_table("message_parts")
    op.drop_index(
        "message_attachments_file_search_idx",
        table_name="message_attachments_file_search",
    )
    op.drop_table("message_attachments_file_search")
    op.drop_index(
        "message_attachments_code_interpreter_idx",
        table_name="message_attachments_code_interpreter",
    )
    op.drop_table("message_attachments_code_interpreter")
    op.drop_table("file_search_call_results")
    op.drop_table("code_interpreter_call_outputs")
    op.drop_table("tool_calls")
    op.drop_table("messages")
    op.drop_table("runs")
    sa.Enum("CODE_INTERPRETER", "FILE_SEARCH", name="toolcalltype").drop(op.get_bind())
    sa.Enum(
        "QUEUED",
        "PENDING",
        "IN_PROGRESS",
        "COMPLETED",
        "FAILED",
        "INCOMPLETE",
        name="runstatus",
    ).drop(op.get_bind())
    sa.Enum(
        "IN_PROGRESS", "COMPLETED", "INCOMPLETE", "PENDING", name="messagestatus"
    ).drop(op.get_bind())
    sa.Enum("USER", "SYSTEM", "ASSISTANT", "DEVELOPER", name="messagerole").drop(
        op.get_bind()
    )
    sa.Enum(
        "INPUT_TEXT", "INPUT_IMAGE", "OUTPUT_TEXT", "REFUSAL", name="messageparttype"
    ).drop(op.get_bind())
    sa.Enum("FILE_PATH", "URL_CITATION", "FILE_CITATION", name="annotationtype").drop(
        op.get_bind()
    )
    sa.Enum("LOGS", "IMAGE", name="codeinterpreteroutputtype").drop(op.get_bind())
    sa.Enum(
        "IN_PROGRESS",
        "SEARCHING",
        "INTERPRETING",
        "COMPLETED",
        "INCOMPLETE",
        "FAILED",
        name="toolcallstatus",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
