"""Add locked column for assistants

Revision ID: 1e252e8386de
Revises: 0a9e2ba4455c
Create Date: 2024-12-10 12:09:50.651786

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e252e8386de"
down_revision: Union[str, None] = "0a9e2ba4455c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistants",
        sa.Column("locked", sa.Boolean(), server_default="false", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "locked")
    # ### end Alembic commands ###
