"""Migration to Assistants API v2: VectorStores(NEW), modified Assistants and Threads

Revision ID: 205658710c84
Revises: 8f4b8eef881c
Create Date: 2024-06-06 23:27:47.190994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205658710c84'
down_revision: Union[str, None] = '8f4b8eef881c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vector_store_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vector_store_id')
    )
    op.create_index(op.f('ix_vector_stores_updated'), 'vector_stores', ['updated'], unique=False)
    op.create_table('file_vector_stores',
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('vector_store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['vector_store_id'], ['vector_stores.id'], )
    )
    op.create_index('file_vector_store_idx', 'file_vector_stores', ['file_id', 'vector_store_id'], unique=True)
    op.create_table('code_interpreter_files_assistants',
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('assistant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], )
    )
    op.create_index('code_interpreter_file_assistant_idx', 'code_interpreter_files_assistants', ['file_id', 'assistant_id'], unique=True)
    op.create_table('code_interpreter_files_threads',
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], )
    )
    op.create_index('code_interpreter_file_thread_idx', 'code_interpreter_files_threads', ['file_id', 'thread_id'], unique=True)
    op.drop_index('file_assistant_idx', table_name='files_assistants')
    op.drop_table('files_assistants')
    op.add_column('assistants', sa.Column('vector_store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assistants', 'vector_stores', ['vector_store_id'], ['id'])
    op.add_column('threads', sa.Column('tools_available', sa.String(), nullable=True))
    op.add_column('threads', sa.Column('vector_store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'threads', 'vector_stores', ['vector_store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threads', type_='foreignkey')
    op.drop_column('threads', 'vector_store_id')
    op.drop_column('threads', 'tools_available')
    op.drop_constraint(None, 'assistants', type_='foreignkey')
    op.drop_column('assistants', 'vector_store_id')
    op.create_table('files_assistants',
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assistant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], name='files_assistants_assistant_id_fkey'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name='files_assistants_file_id_fkey')
    )
    op.create_index('file_assistant_idx', 'files_assistants', ['file_id', 'assistant_id'], unique=True)
    op.drop_index('code_interpreter_file_thread_idx', table_name='code_interpreter_files_threads')
    op.drop_table('code_interpreter_files_threads')
    op.drop_index('code_interpreter_file_assistant_idx', table_name='code_interpreter_files_assistants')
    op.drop_table('code_interpreter_files_assistants')
    op.drop_index('file_vector_store_idx', table_name='file_vector_stores')
    op.drop_table('file_vector_stores')
    op.drop_index(op.f('ix_vector_stores_updated'), table_name='vector_stores')
    op.drop_table('vector_stores')
    # ### end Alembic commands ###
