"""add columns for assistant management options

Revision ID: 22ef0e00b450
Revises: a61dd1e1aca7
Create Date: 2024-01-17 15:30:01.690819

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22ef0e00b450"
down_revision: Union[str, None] = "a61dd1e1aca7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classes", sa.Column("any_can_create_assistant", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "classes", sa.Column("any_can_publish_assistant", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classes", "any_can_publish_assistant")
    op.drop_column("classes", "any_can_create_assistant")
    # ### end Alembic commands ###
