"""Add API Key table

Revision ID: 29bf10fa9462
Revises: 8c1d49d7fe53
Create Date: 2024-11-21 21:37:53.126293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29bf10fa9462'
down_revision: Union[str, None] = '8c1d49d7fe53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('azure_endpoint', sa.String(), nullable=True),
    sa.Column('azure_api_version', sa.String(), nullable=True),
    sa.Column('available_as_default', sa.Boolean(), nullable=True),
    sa.Column('azure_endpoint_coalesced', sa.String(), sa.Computed("COALESCE(azure_endpoint, '')", ), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key', 'provider', 'azure_endpoint_coalesced', name='_key_endpoint_provider_uc')
    )
    op.add_column('classes', sa.Column('api_key_id', sa.Integer(), nullable=True))
    op.create_foreign_key('_classes_api_keys_fk', 'classes', 'api_keys', ['api_key_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_classes_api_keys_fk', 'classes', type_='foreignkey')
    op.drop_column('classes', 'api_key_id')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
