"""Add can_share_assistants permission

Revision ID: 2b8a809f389b
Revises: a0e423503265
Create Date: 2025-08-28 19:14:51.599247

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b8a809f389b"
down_revision: Union[str, None] = "a0e423503265"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classes", sa.Column("any_can_share_assistant", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classes", "any_can_share_assistant")
    # ### end Alembic commands ###
