"""Add Hide MCP Details

Revision ID: 371b3a44a211
Revises: 7a2c06fb4b7c
Create Date: 2025-12-24 23:26:28.308666

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "371b3a44a211"
down_revision: Union[str, None] = "7a2c06fb4b7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistants",
        sa.Column(
            "hide_mcp_server_call_details",
            sa.Boolean(),
            server_default="true",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "hide_mcp_server_call_details")
    # ### end Alembic commands ###
