"""AI Summaries

Revision ID: 392821b96cb0
Revises: 532eea36d1c6
Create Date: 2025-01-27 18:59:23.737683

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "392821b96cb0"
down_revision: Union[str, None] = "532eea36d1c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "periodic_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_task_name", "periodic_tasks", ["task_name"], unique=True)
    op.create_table(
        "scheduled_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["periodic_tasks.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_task_id", "scheduled_jobs", ["task_id"], unique=False)
    op.add_column(
        "classes",
        sa.Column("last_summary_sent_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "users_classes",
        sa.Column(
            "subscribed_to_summaries",
            sa.Boolean(),
            server_default="true",
            nullable=True,
        ),
    )
    op.add_column(
        "users_classes",
        sa.Column("last_summary_sent_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_classes", "last_summary_sent_at")
    op.drop_column("users_classes", "subscribed_to_summaries")
    op.drop_column("classes", "last_summary_sent_at")
    op.drop_index("idx_task_id", table_name="scheduled_jobs")
    op.drop_table("scheduled_jobs")
    op.drop_index("idx_task_name", table_name="periodic_tasks")
    op.drop_table("periodic_tasks")
    # ### end Alembic commands ###
