"""Add resource_link_id in LTIClass

Revision ID: 3cc56efe20a8
Revises: a384f2bfddf4
Create Date: 2026-02-10 18:00:43.449645

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3cc56efe20a8"
down_revision: Union[str, None] = "a384f2bfddf4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lti_classes", sa.Column("resource_link_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lti_classes", "resource_link_id")
    # ### end Alembic commands ###
