"""Clean Up after migration
Revision ID: 443687e4b64c
Revises: ccc53879e832
Create Date: 2024-06-20 11:35:27.408269
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "443687e4b64c"
down_revision: Union[str, None] = "ccc53879e832"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("file_assistant_idx", table_name="files_assistants")
    op.drop_table("files_assistants")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files_assistants",
        sa.Column("file_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("assistant_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistants.id"],
            name="files_assistants_assistant_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name="files_assistants_file_id_fkey"
        ),
    )
    op.create_index(
        "file_assistant_idx",
        "files_assistants",
        ["file_id", "assistant_id"],
        unique=True,
    )
    # ### end Alembic commands ###
