"""Add Reasoning

Revision ID: 4452de1e99bc
Revises: 46bb3044681e
Create Date: 2025-09-05 20:35:59.169141

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4452de1e99bc"
down_revision: Union[str, None] = "46bb3044681e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reasoning_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reasoning_id", sa.String(), nullable=True),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("output_index", sa.Integer(), nullable=False),
        sa.Column("encrypted_content", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "COMPLETED", "INCOMPLETE", name="reasoningstatus"),
            nullable=False,
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("completed", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reasoning_content_parts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reasoning_step_id", sa.Integer(), nullable=False),
        sa.Column("part_index", sa.Integer(), nullable=False),
        sa.Column("content_text", sa.String(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["reasoning_step_id"], ["reasoning_steps.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reasoning_summary_parts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reasoning_step_id", sa.Integer(), nullable=False),
        sa.Column("part_index", sa.Integer(), nullable=False),
        sa.Column("summary_text", sa.String(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["reasoning_step_id"], ["reasoning_steps.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reasoning_summary_parts")
    op.drop_table("reasoning_content_parts")
    op.drop_table("reasoning_steps")
    sa.Enum("IN_PROGRESS", "COMPLETED", "INCOMPLETE", name="reasoningstatus").drop(
        op.get_bind(), checkfirst=False
    )
    # ### end Alembic commands ###
