"""Add private field for Classes

Revision ID: 44edbf2cecbc
Revises: 7d6dde851734
Create Date: 2024-06-25 18:51:13.610411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44edbf2cecbc"
down_revision: Union[str, None] = "7d6dde851734"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("classes", sa.Column("private", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classes", "private")
    # ### end Alembic commands ###
