"""Add Web Search

Revision ID: 46bb3044681e
Revises: dc52d12c16db
Create Date: 2025-09-05 17:36:37.103714

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46bb3044681e"
down_revision: Union[str, None] = "dc52d12c16db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

column_name = "type"
enum_name = "toolcalltype"
temp_enum_name = f"temp_{enum_name}"
old_values = ("CODE_INTERPRETER", "FILE_SEARCH")
new_values = ("WEB_SEARCH", *old_values)
old_type = sa.Enum(*old_values, name=enum_name)
new_type = sa.Enum(*new_values, name=enum_name)
temp_type = sa.Enum(*new_values, name=temp_enum_name)

table_name = "tool_calls"
column_name = "type"
simplified_table = sa.sql.table(
    table_name, sa.Column(column_name, new_type, nullable=False)
)


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    temp_type.create(op.get_bind(), checkfirst=False)

    with op.batch_alter_table(table_name) as batch_op:
        batch_op.alter_column(
            column_name,
            existing_type=old_type,
            type_=temp_type,
            postgresql_using=f"{column_name}::text::{temp_enum_name}",
            existing_nullable=False,
        )

    old_type.drop(op.get_bind(), checkfirst=False)
    new_type.create(op.get_bind(), checkfirst=False)

    with op.batch_alter_table(table_name) as batch_op:
        batch_op.alter_column(
            column_name,
            existing_type=temp_type,
            type_=new_type,
            postgresql_using=f"{column_name}::text::{enum_name}",
            existing_nullable=False,
        )

    temp_type.drop(op.get_bind(), checkfirst=False)

    op.create_table(
        "web_search_call_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("SEARCH", "FIND", "OPEN_PAGE", name="websearchactiontype"),
            nullable=False,
        ),
        sa.Column("tool_call_id", sa.Integer(), nullable=False),
        sa.Column("query", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("pattern", sa.String(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id"], ["tool_calls.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "web_search_call_search_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("web_search_call_action_id", sa.Integer(), nullable=False),
        sa.Column("tool_call_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id"], ["tool_calls.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["web_search_call_action_id"],
            ["web_search_call_actions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove rows with the new enum value to avoid issues during downgrade
    op.execute(simplified_table.delete().where(simplified_table.c.type == "WEB_SEARCH"))

    temp_type.create(op.get_bind(), checkfirst=False)

    with op.batch_alter_table(table_name) as batch_op:
        batch_op.alter_column(
            column_name,
            existing_type=new_type,
            type_=temp_type,
            postgresql_using=f"{column_name}::text::{temp_enum_name}",
            existing_nullable=False,
        )

    new_type.drop(op.get_bind(), checkfirst=False)
    old_type.create(op.get_bind(), checkfirst=False)

    with op.batch_alter_table(table_name) as batch_op:
        batch_op.alter_column(
            column_name,
            existing_type=temp_type,
            type_=old_type,
            postgresql_using=f"{column_name}::text::{enum_name}",
            existing_nullable=False,
        )

    temp_type.drop(op.get_bind(), checkfirst=False)

    op.drop_table("web_search_call_search_sources")
    op.drop_table("web_search_call_actions")
    sa.Enum("SEARCH", "FIND", "OPEN_PAGE", name="websearchactiontype").drop(
        op.get_bind(), checkfirst=False
    )
    # ### end Alembic commands ###
