"""added lecture_video_id to threads

Revision ID: 4aed51ccae36
Revises: d4843142e8de
Create Date: 2026-02-18 15:18:06.167233

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4aed51ccae36"
down_revision: Union[str, None] = "d4843142e8de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("threads", sa.Column("lecture_video_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_threads_lecture_video_id_lecture_video",
        "threads",
        "lecture_videos",
        ["lecture_video_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_threads_lecture_video_id_lecture_video", "threads", type_="foreignkey"
    )
    op.drop_column("threads", "lecture_video_id")
    # ### end Alembic commands ###
