"""Add Class Delete FK dependency

Revision ID: 4b6d8576721d
Revises: 39fad082e71b
Create Date: 2024-09-08 23:03:32.311465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6d8576721d'
down_revision: Union[str, None] = '39fad082e71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('code_interpreter_calls_thread_id_fkey', 'code_interpreter_calls', type_='foreignkey')
    op.create_foreign_key('code_interpreter_calls_thread_id_fkey', 'code_interpreter_calls', 'threads', ['thread_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('files_class_id_fkey', 'files', type_='foreignkey')
    op.drop_constraint('files_uploader_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key('files_class_id_fkey', 'files', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('files_uploader_id_fkey', 'files', 'users', ['uploader_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_classes_class_id_fkey', 'users_classes', type_='foreignkey')
    op.drop_constraint('users_classes_user_id_fkey', 'users_classes', type_='foreignkey')
    op.create_foreign_key('users_classes_class_id_fkey', 'users_classes', 'classes', ['class_id'], ['id'], ondelete='cascade')
    op.create_foreign_key('users_classes_user_id_fkey', 'users_classes', 'users', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_classes_class_id_fkey', 'users_classes', type_='foreignkey')
    op.drop_constraint('users_classes_user_id_fkey', 'users_classes', type_='foreignkey')
    op.create_foreign_key('users_classes_user_id_fkey', 'users_classes', 'users', ['user_id'], ['id'])
    op.create_foreign_key('users_classes_class_id_fkey', 'users_classes', 'classes', ['class_id'], ['id'])
    op.drop_constraint('files_class_id_fkey', 'files', type_='foreignkey')
    op.drop_constraint('files_uploader_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key('files_uploader_id_fkey', 'files', 'users', ['uploader_id'], ['id'])
    op.create_foreign_key('files_class_id_fkey', 'files', 'classes', ['class_id'], ['id'])
    op.drop_constraint('code_interpreter_calls_thread_id_fkey', 'code_interpreter_calls', type_='foreignkey')
    op.create_foreign_key('code_interpreter_calls_thread_id_fkey', 'code_interpreter_calls', 'threads', ['thread_id'], ['id'])
    # ### end Alembic commands ###
