"""User Agreements

Revision ID: 52dfd11d4503
Revises: dcf2fe04f74f
Create Date: 2025-02-19 13:53:24.904399

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52dfd11d4503"
down_revision: Union[str, None] = "dcf2fe04f74f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agreements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agreements_updated"), "agreements", ["updated"], unique=False
    )
    op.create_table(
        "agreement_policies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("agreement_id", sa.Integer(), nullable=False),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=True),
        sa.Column("not_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("apply_to_all", sa.Boolean(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agreement_id"], ["agreements.id"], ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agreement_policies_agreement_id"),
        "agreement_policies",
        ["agreement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agreement_policies_updated"),
        "agreement_policies",
        ["updated"],
        unique=False,
    )
    op.create_table(
        "agreement_acceptances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("agreement_id", sa.Integer(), nullable=False),
        sa.Column("policy_id", sa.Integer(), nullable=False),
        sa.Column(
            "accepted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["agreement_id"],
            ["agreements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["agreement_policies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "agreement_id", name="_user_agreement_uc"),
    )
    op.create_index(
        op.f("ix_agreement_acceptances_agreement_id"),
        "agreement_acceptances",
        ["agreement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agreement_acceptances_policy_id"),
        "agreement_acceptances",
        ["policy_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agreement_acceptances_user_id"),
        "agreement_acceptances",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "agreement_policies_external_logins",
        sa.Column("agreement_policy_id", sa.Integer(), nullable=True),
        sa.Column("provider_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agreement_policy_id"],
            ["agreement_policies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["external_login_providers.id"],
        ),
    )
    op.create_index(
        "agreement_policy_external_login_idx",
        "agreement_policies_external_logins",
        ["agreement_policy_id", "provider_id"],
        unique=True,
    )
    op.create_index(
        "ix_external_login_providers_name",
        "external_login_providers",
        ["name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_external_login_providers_name", table_name="external_login_providers"
    )
    op.drop_index(
        "agreement_policy_external_login_idx",
        table_name="agreement_policies_external_logins",
    )
    op.drop_table("agreement_policies_external_logins")
    op.drop_index(
        op.f("ix_agreement_acceptances_user_id"), table_name="agreement_acceptances"
    )
    op.drop_index(
        op.f("ix_agreement_acceptances_policy_id"), table_name="agreement_acceptances"
    )
    op.drop_index(
        op.f("ix_agreement_acceptances_agreement_id"),
        table_name="agreement_acceptances",
    )
    op.drop_table("agreement_acceptances")
    op.drop_index(
        op.f("ix_agreement_policies_updated"), table_name="agreement_policies"
    )
    op.drop_index(
        op.f("ix_agreement_policies_agreement_id"), table_name="agreement_policies"
    )
    op.drop_table("agreement_policies")
    op.drop_index(op.f("ix_agreements_updated"), table_name="agreements")
    op.drop_table("agreements")
    # ### end Alembic commands ###
