"""Add LTIClass

Revision ID: 537e633357fb
Revises: 67c478e2ea51
Create Date: 2025-12-19 02:23:56.191775

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "537e633357fb"
down_revision: Union[str, None] = "67c478e2ea51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    PLATFORM_ENUM = sa.Enum("CANVAS", name="lmsplatform")
    op.create_table(
        "lti_classes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("registration_id", sa.Integer(), nullable=False),
        sa.Column(
            "lti_status", sa.Enum("LINKED", "ERROR", name="ltistatus"), nullable=False
        ),
        sa.Column("last_synced", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_error", sa.String(), nullable=True),
        sa.Column("setup_user_id", sa.Integer(), nullable=True),
        sa.Column("course_id", sa.String(), nullable=False),
        sa.Column("course_name", sa.String(), nullable=True),
        sa.Column("course_code", sa.String(), nullable=True),
        sa.Column("course_term", sa.String(), nullable=True),
        sa.Column("class_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["class_id"], ["classes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["registration_id"], ["lti_registrations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["setup_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "registration_id", "course_id", name="_lti_registration_course_id_uc"
        ),
    )
    op.add_column(
        "lti_classes",
        sa.Column("lti_platform", PLATFORM_ENUM, nullable=False),
    )
    op.create_index(
        "idx_lti_classes_class_id", "lti_classes", ["class_id"], unique=False
    )
    op.create_index(
        "idx_lti_classes_registration_id",
        "lti_classes",
        ["registration_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_lti_classes_registration_id", table_name="lti_classes")
    op.drop_index("idx_lti_classes_class_id", table_name="lti_classes")
    op.drop_table("lti_classes")
    sa.Enum("LINKED", "ERROR", name="ltistatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
