"""Email as ExternalLogin provider

Revision ID: 544ba10e2086
Revises: 1e252e8386de
Create Date: 2025-01-07 14:32:47.674635

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "544ba10e2086"
down_revision: Union[str, None] = "1e252e8386de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_user_provider_uc", "external_logins", type_="unique")
    op.create_index(
        "idx_user_provider", "external_logins", ["user_id", "provider"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_provider", table_name="external_logins")
    op.create_unique_constraint(
        "_user_provider_uc", "external_logins", ["user_id", "provider"]
    )
    # ### end Alembic commands ###
