"""Store LMS Tenant in Class table


Revision ID: 58003b4b1f16
Revises: 61666311d80b
Create Date: 2025-04-10 19:25:59.152725

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58003b4b1f16"
down_revision: Union[str, None] = "61666311d80b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("classes", sa.Column("lms_tenant", sa.String(), nullable=True))
    op.add_column(
        "classes",
        sa.Column("lms_type", sa.Enum("CANVAS", name="lmstype"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classes", "lms_tenant")
    op.drop_column("classes", "lms_type")
    # ### end Alembic commands ###
