"""Add LMS Sync dependencies

Revision ID: 5acfd7c7485f
Revises: 44edbf2cecbc
Create Date: 2024-08-22 22:03:08.832458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acfd7c7485f'
down_revision: Union[str, None] = '44edbf2cecbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('CANVAS', name='lmstype')
    op.create_table('lms_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lms_id', sa.Integer(), nullable=False),
    sa.Column('lms_tenant', sa.String(), nullable=False),
    sa.Column('lms_type', sa.Enum('CANVAS', name='lmstype'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('course_code', sa.String(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lms_id', 'lms_tenant', 'lms_type', name='_id_lms_uc')
    )
    sa.Enum('NONE', 'AUTHORIZED', 'LINKED', 'DISMISSED', 'ERROR', name='lmsstatus').create(op.get_bind())
    op.add_column('classes', sa.Column('lms_status', sa.Enum('NONE', 'AUTHORIZED', 'LINKED', 'DISMISSED', 'ERROR', name='lmsstatus'), nullable=True))
    op.add_column('classes', sa.Column('lms_class_id', sa.Integer(), nullable=True))
    op.add_column('classes', sa.Column('lms_user_id', sa.Integer(), nullable=True))
    op.add_column('classes', sa.Column('lms_course_id', sa.Integer(), nullable=True))
    op.add_column('classes', sa.Column('lms_access_token', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('lms_refresh_token', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('lms_expires_in', sa.Integer(), nullable=True))
    op.add_column('classes', sa.Column('lms_token_added_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('classes', sa.Column('lms_last_synced', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('classes_lms_class_id_fkey', 'classes', 'lms_classes', ['lms_class_id'], ['id'])
    op.create_foreign_key('classes_lms_user_id_fkey', 'classes', 'users', ['lms_user_id'], ['id'])
    op.add_column('users_classes', sa.Column('lms_type', sa.Enum('CANVAS', name='lmstype'), nullable=True))
    op.add_column('users_classes', sa.Column('lms_tenant', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_classes', 'lms_tenant')
    op.drop_column('users_classes', 'lms_type')
    op.drop_constraint('classes_lms_class_id_fkey', 'classes', type_='foreignkey')
    op.drop_constraint('classes_lms_user_id_fkey', 'classes', type_='foreignkey')
    op.drop_column('classes', 'lms_last_synced')
    op.drop_column('classes', 'lms_token_added_at')
    op.drop_column('classes', 'lms_expires_in')
    op.drop_column('classes', 'lms_refresh_token')
    op.drop_column('classes', 'lms_access_token')
    op.drop_column('classes', 'lms_course_id')
    op.drop_column('classes', 'lms_user_id')
    op.drop_column('classes', 'lms_class_id')
    op.drop_column('classes', 'lms_status')
    op.drop_table('lms_classes')
    sa.Enum('CANVAS', name='lmstype').drop(op.get_bind())
    sa.Enum('NONE', 'AUTHORIZED', 'LINKED', 'DISMISSED', 'ERROR', name='lmsstatus').drop(op.get_bind())
    # ### end Alembic commands ###
