"""User Agreements

Revision ID: 5f362b496d32
Revises: b26bb2fb8a1b
Create Date: 2025-02-04 20:24:38.563183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f362b496d32'
down_revision: Union[str, None] = 'b26bb2fb8a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_agreement_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('show_all', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_agreement_categories_updated'), 'user_agreement_categories', ['updated'], unique=False)
    op.create_table('user_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('always_display', sa.Boolean(), nullable=True),
    sa.Column('apply_to_all', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['user_agreement_categories.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_agreements_updated'), 'user_agreements', ['updated'], unique=False)
    op.create_table('user_agreement_acceptances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['user_agreements.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_agreements_external_logins',
    sa.Column('agreement_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['user_agreements.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['external_login_providers.id'], )
    )
    op.create_index('user_agreement_external_login_idx', 'user_agreements_external_logins', ['agreement_id', 'provider_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_agreement_external_login_idx', table_name='user_agreements_external_logins')
    op.drop_table('user_agreements_external_logins')
    op.drop_table('user_agreement_acceptances')
    op.drop_index(op.f('ix_user_agreements_updated'), table_name='user_agreements')
    op.drop_table('user_agreements')
    op.drop_index(op.f('ix_user_agreement_categories_updated'), table_name='user_agreement_categories')
    op.drop_table('user_agreement_categories')
    # ### end Alembic commands ###
