"""add column for hiding prompt

Revision ID: 6095509a2761
Revises: ef79c15112d7
Create Date: 2024-01-18 16:26:57.094040

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6095509a2761"
down_revision: Union[str, None] = "ef79c15112d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistants", sa.Column("hide_prompt", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "hide_prompt")
    # ### end Alembic commands ###
