"""Assistant Interaction Modes

Revision ID: 61666311d80b
Revises: 52dfd11d4503
Create Date: 2025-03-24 10:13:39.789867

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61666311d80b"
down_revision: Union[str, None] = "52dfd11d4503"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("CHAT", "LIVE_AUDIO", name="assistantinteractionmode").create(op.get_bind())
    op.add_column(
        "assistants",
        sa.Column(
            "interaction_mode",
            sa.Enum("CHAT", "LIVE_AUDIO", name="assistantinteractionmode"),
            server_default="CHAT",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "interaction_mode")
    sa.Enum("CHAT", "LIVE_AUDIO", name="assistantinteractionmode").drop(op.get_bind())
    # ### end Alembic commands ###
