"""Add SSO Merging dependencies

Revision ID: 61d1eb446410
Revises: 5acfd7c7485f
Create Date: 2024-09-05 21:59:55.250425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d1eb446410'
down_revision: Union[str, None] = '5acfd7c7485f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_logins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users_classes', 'sso_id')
    op.drop_column('users_classes', 'sso_tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_classes', sa.Column('sso_tenant', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users_classes', sa.Column('sso_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('external_logins')
    # ### end Alembic commands ###
