"""Add LTIOIDCSession

Revision ID: 67c478e2ea51
Revises: e920bdf08505
Create Date: 2025-12-18 23:25:33.883783

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67c478e2ea51"
down_revision: Union[str, None] = "e920bdf08505"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lti_oidc_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("nonce_sha256", sa.String(), nullable=False),
        sa.Column("issuer", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("deployment_id", sa.String(), nullable=True),
        sa.Column("redirect_uri", sa.String(), nullable=True),
        sa.Column("target_link_uri", sa.String(), nullable=True),
        sa.Column("login_hint", sa.String(), nullable=True),
        sa.Column("lti_message_hint", sa.String(), nullable=True),
        sa.Column("extra", sa.String(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state"),
    )
    op.create_index(
        "idx_lti_oidc_consumed_at", "lti_oidc_sessions", ["consumed_at"], unique=False
    )
    op.create_index(
        "idx_lti_oidc_expires_at", "lti_oidc_sessions", ["expires_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_lti_oidc_expires_at", table_name="lti_oidc_sessions")
    op.drop_index("idx_lti_oidc_consumed_at", table_name="lti_oidc_sessions")
    op.drop_table("lti_oidc_sessions")
    # ### end Alembic commands ###
