"""Add Azure Region

Revision ID: 6bc8a757a63f
Revises: 58003b4b1f16
Create Date: 2025-04-14 18:47:36.595165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6bc8a757a63f"
down_revision: Union[str, None] = "58003b4b1f16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_keys", sa.Column("region", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_keys", "region")
    # ### end Alembic commands ###
