"""AI Summaries

Revision ID: 6c8df8c76cbb
Revises: 532eea36d1c6
Create Date: 2025-01-23 16:13:15.973839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8df8c76cbb'
down_revision: Union[str, None] = '532eea36d1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('last_summary_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users_classes', sa.Column('subscribed_to_summaries', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('users_classes', sa.Column('last_summary_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_classes', 'last_summary_sent_at')
    op.drop_column('users_classes', 'subscribed_to_summaries')
    op.drop_column('classes', 'last_summary_sent_at')
    # ### end Alembic commands ###
