"""Add LTI

Revision ID: 70728fb7d6c6
Revises: a54f5dd3ac9d
Create Date: 2025-12-20 19:18:32.378047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70728fb7d6c6'
down_revision: Union[str, None] = 'a54f5dd3ac9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lti_oidc_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('nonce_sha256', sa.String(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('deployment_id', sa.String(), nullable=True),
    sa.Column('redirect_uri', sa.String(), nullable=True),
    sa.Column('target_link_uri', sa.String(), nullable=True),
    sa.Column('login_hint', sa.String(), nullable=True),
    sa.Column('lti_message_hint', sa.String(), nullable=True),
    sa.Column('extra', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.create_index('idx_lti_oidc_consumed_at', 'lti_oidc_sessions', ['consumed_at'], unique=False)
    op.create_index('idx_lti_oidc_expires_at', 'lti_oidc_sessions', ['expires_at'], unique=False)
    op.create_table('lti_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('auth_login_url', sa.String(), nullable=False),
    sa.Column('auth_token_url', sa.String(), nullable=False),
    sa.Column('key_set_url', sa.String(), nullable=False),
    sa.Column('token_algorithm', sa.Enum('RS256', name='ltitokenalgorithm'), nullable=False),
    sa.Column('lms_platform', sa.Enum('CANVAS', name='lmsplatform'), nullable=True),
    sa.Column('canvas_account_name', sa.String(), nullable=True),
    sa.Column('openid_configuration', sa.String(), nullable=True),
    sa.Column('registration_data', sa.String(), nullable=True),
    sa.Column('admin_name', sa.String(), nullable=True),
    sa.Column('admin_email', sa.String(), nullable=True),
    sa.Column('friendly_name', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='ltiregistrationreviewstatus'), server_default='PENDING', nullable=True),
    sa.Column('internal_notes', sa.String(), nullable=True),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.Column('review_by_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['review_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lti_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('lti_status', sa.Enum('LINKED', 'ERROR', name='ltistatus'), nullable=False),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.String(), nullable=True),
    sa.Column('context_memberships_url', sa.String(), nullable=True),
    sa.Column('setup_user_id', sa.Integer(), nullable=True),
    sa.Column('lti_platform', sa.Enum('CANVAS', name='lmsplatform'), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=True),
    sa.Column('course_code', sa.String(), nullable=True),
    sa.Column('course_term', sa.String(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registration_id'], ['lti_registrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setup_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id', 'course_id', name='_lti_registration_course_id_uc')
    )
    op.create_index('idx_lti_classes_class_id', 'lti_classes', ['class_id'], unique=False)
    op.create_index('idx_lti_classes_registration_id', 'lti_classes', ['registration_id'], unique=False)
    op.create_table('lti_registrations_institutions',
    sa.Column('lti_registration_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['lti_registration_id'], ['lti_registrations.id'], )
    )
    op.create_index('lti_registration_institution_idx', 'lti_registrations_institutions', ['lti_registration_id', 'institution_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('lti_registration_institution_idx', table_name='lti_registrations_institutions')
    op.drop_table('lti_registrations_institutions')
    op.drop_index('idx_lti_classes_registration_id', table_name='lti_classes')
    op.drop_index('idx_lti_classes_class_id', table_name='lti_classes')
    op.drop_table('lti_classes')
    op.drop_table('lti_registrations')
    op.drop_index('idx_lti_oidc_expires_at', table_name='lti_oidc_sessions')
    op.drop_index('idx_lti_oidc_consumed_at', table_name='lti_oidc_sessions')
    op.drop_table('lti_oidc_sessions')
    sa.Enum("CANVAS", name="lmsplatform").drop(op.get_bind(), checkfirst=True)
    sa.Enum("PENDING", "APPROVED", "REJECTED", name="ltiregistrationreviewstatus").drop(
        op.get_bind(), checkfirst=True
    )
    sa.Enum("RS256", name="ltitokenalgorithm").drop(op.get_bind(), checkfirst=True)
    sa.Enum("LINKED", "ERROR", name="ltistatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
