"""Add MCP

Revision ID: 7a2c06fb4b7c
Revises: 70728fb7d6c6
Create Date: 2025-12-23 15:52:03.098040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import or_


# revision identifiers, used by Alembic.
revision: str = "7a2c06fb4b7c"
down_revision: Union[str, None] = "70728fb7d6c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

toolcalltype_column_name = "type"
toolcalltype_enum_name = "toolcalltype"
toolcalltype_temp_enum_name = f"temp_{toolcalltype_enum_name}"
toolcalltype_old_values = (
    "CODE_INTERPRETER",
    "FILE_SEARCH",
    "WEB_SEARCH",
)
toolcalltype_new_values = ("MCP_SERVER", "MCP_LIST_TOOLS", *toolcalltype_old_values)
toolcalltype_old_type = sa.Enum(*toolcalltype_old_values, name=toolcalltype_enum_name)
toolcalltype_new_type = sa.Enum(*toolcalltype_new_values, name=toolcalltype_enum_name)
toolcalltype_temp_type = sa.Enum(
    *toolcalltype_new_values, name=toolcalltype_temp_enum_name
)

toolcalltype_table_name = "tool_calls"
toolcalltype_column_name = "type"
toolcalltype_simplified_table = sa.sql.table(
    toolcalltype_table_name,
    sa.Column(toolcalltype_column_name, toolcalltype_new_type, nullable=False),
)

toolcallstatus_column_name = "status"
toolcallstatus_enum_name = "toolcallstatus"
toolcallstatus_temp_enum_name = f"temp_{toolcallstatus_enum_name}"
toolcallstatus_old_values = (
    "IN_PROGRESS",
    "SEARCHING",
    "INTERPRETING",
    "COMPLETED",
    "INCOMPLETE",
    "FAILED",
)
toolcallstatus_new_values = ("CALLING", *toolcallstatus_old_values)
toolcallstatus_old_type = sa.Enum(
    *toolcallstatus_old_values, name=toolcallstatus_enum_name
)
toolcallstatus_new_type = sa.Enum(
    *toolcallstatus_new_values, name=toolcallstatus_enum_name
)
toolcallstatus_temp_type = sa.Enum(
    *toolcallstatus_new_values, name=toolcallstatus_temp_enum_name
)

toolcallstatus_table_name = "tool_calls"
toolcallstatus_column_name = "status"
toolcallstatus_simplified_table = sa.sql.table(
    toolcallstatus_table_name,
    sa.Column(toolcallstatus_column_name, toolcallstatus_new_type, nullable=False),
)


def upgrade() -> None:
    toolcalltype_temp_type.create(op.get_bind(), checkfirst=False)
    toolcallstatus_temp_type.create(op.get_bind(), checkfirst=False)

    with op.batch_alter_table(toolcalltype_table_name) as batch_op:
        batch_op.alter_column(
            toolcalltype_column_name,
            existing_type=toolcalltype_old_type,
            type_=toolcalltype_temp_type,
            postgresql_using=f"{toolcalltype_column_name}::text::{toolcalltype_temp_enum_name}",
            existing_nullable=False,
        )
        batch_op.alter_column(
            toolcallstatus_column_name,
            existing_type=toolcallstatus_old_type,
            type_=toolcallstatus_temp_type,
            postgresql_using=f"{toolcallstatus_column_name}::text::{toolcallstatus_temp_enum_name}",
            existing_nullable=False,
        )

    toolcalltype_old_type.drop(op.get_bind(), checkfirst=False)
    toolcalltype_new_type.create(op.get_bind(), checkfirst=False)
    toolcallstatus_old_type.drop(op.get_bind(), checkfirst=False)
    toolcallstatus_new_type.create(op.get_bind(), checkfirst=False)

    with op.batch_alter_table(toolcalltype_table_name) as batch_op:
        batch_op.alter_column(
            toolcalltype_column_name,
            existing_type=toolcalltype_temp_type,
            type_=toolcalltype_new_type,
            postgresql_using=f"{toolcalltype_column_name}::text::{toolcalltype_enum_name}",
            existing_nullable=False,
        )
        batch_op.alter_column(
            toolcallstatus_column_name,
            existing_type=toolcallstatus_temp_type,
            type_=toolcallstatus_new_type,
            postgresql_using=f"{toolcallstatus_column_name}::text::{toolcallstatus_enum_name}",
            existing_nullable=False,
        )

    toolcalltype_temp_type.drop(op.get_bind(), checkfirst=False)
    toolcallstatus_temp_type.drop(op.get_bind(), checkfirst=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_server_tools",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("server_url", sa.String(), nullable=False),
        sa.Column("server_label", sa.String(), nullable=False),
        sa.Column("headers", sa.String(), nullable=True),
        sa.Column("authorization_token", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mcp_server_tools_server_label"),
        "mcp_server_tools",
        ["server_label"],
        unique=True,
    )
    op.create_table(
        "mcp_server_tool_assistant_associations",
        sa.Column("mcp_server_tool_id", sa.Integer(), nullable=True),
        sa.Column("assistant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mcp_server_tool_id"],
            ["mcp_server_tools.id"],
        ),
    )
    op.create_index(
        "mcp_server_tool_assistant_idx",
        "mcp_server_tool_assistant_associations",
        ["mcp_server_tool_id", "assistant_id"],
        unique=True,
    )
    op.create_table(
        "mcp_server_tool_thread_associations",
        sa.Column("mcp_server_tool_id", sa.Integer(), nullable=True),
        sa.Column("thread_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mcp_server_tool_id"],
            ["mcp_server_tools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
    )
    op.create_index(
        "mcp_server_tool_thread_idx",
        "mcp_server_tool_thread_associations",
        ["mcp_server_tool_id", "thread_id"],
        unique=True,
    )
    op.create_table(
        "mcp_server_tool_run_associations",
        sa.Column("mcp_server_tool_id", sa.Integer(), nullable=True),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mcp_server_tool_id"],
            ["mcp_server_tools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
    )
    op.create_index(
        "mcp_server_tool_run_idx",
        "mcp_server_tool_run_associations",
        ["mcp_server_tool_id", "run_id"],
        unique=True,
    )
    op.create_table(
        "mcp_list_tools_tools",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("input_schema", sa.String(), nullable=True),
        sa.Column("annotations", sa.String(), nullable=True),
        sa.Column("mcp_server_tool_id", sa.Integer(), nullable=True),
        sa.Column("tool_call_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mcp_server_tool_id"], ["mcp_server_tools.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id"], ["tool_calls.id"], ondelete="CASCADE"
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "tool_calls", sa.Column("mcp_server_tool_id", sa.Integer(), nullable=True)
    )
    op.add_column("tool_calls", sa.Column("mcp_tool_name", sa.String(), nullable=True))
    op.add_column(
        "tool_calls", sa.Column("mcp_server_label", sa.String(), nullable=True)
    )
    op.add_column("tool_calls", sa.Column("mcp_arguments", sa.String(), nullable=True))
    op.add_column("tool_calls", sa.Column("mcp_output", sa.String(), nullable=True))
    op.add_column("tool_calls", sa.Column("error", sa.String(), nullable=True))
    op.create_foreign_key(
        "tool_calls_mcp_server_tool_id_fkey",
        "tool_calls",
        "mcp_server_tools",
        ["mcp_server_tool_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        toolcalltype_simplified_table.delete().where(
            or_(
                toolcalltype_simplified_table.c.type == "MCP_SERVER",
                toolcalltype_simplified_table.c.type == "MCP_LIST_TOOLS",
            )
        )
    )
    op.execute(
        toolcallstatus_simplified_table.delete().where(
            toolcallstatus_simplified_table.c.status == "CALLING"
        )
    )

    toolcalltype_temp_type.create(op.get_bind(), checkfirst=False)
    toolcallstatus_temp_type.create(op.get_bind(), checkfirst=False)

    with op.batch_alter_table(toolcalltype_table_name) as batch_op:
        batch_op.alter_column(
            toolcalltype_column_name,
            existing_type=toolcalltype_new_type,
            type_=toolcalltype_temp_type,
            postgresql_using=f"{toolcalltype_column_name}::text::{toolcalltype_temp_enum_name}",
            existing_nullable=False,
        )
        batch_op.alter_column(
            toolcallstatus_column_name,
            existing_type=toolcallstatus_new_type,
            type_=toolcallstatus_temp_type,
            postgresql_using=f"{toolcallstatus_column_name}::text::{toolcallstatus_temp_enum_name}",
            existing_nullable=False,
        )

    toolcalltype_new_type.drop(op.get_bind(), checkfirst=False)
    toolcalltype_old_type.create(op.get_bind(), checkfirst=False)
    toolcallstatus_new_type.drop(op.get_bind(), checkfirst=False)
    toolcallstatus_old_type.create(op.get_bind(), checkfirst=False)

    with op.batch_alter_table(toolcalltype_table_name) as batch_op:
        batch_op.alter_column(
            toolcalltype_column_name,
            existing_type=toolcalltype_temp_type,
            type_=toolcalltype_old_type,
            postgresql_using=f"{toolcalltype_column_name}::text::{toolcalltype_enum_name}",
            existing_nullable=False,
        )
        batch_op.alter_column(
            toolcallstatus_column_name,
            existing_type=toolcallstatus_temp_type,
            type_=toolcallstatus_old_type,
            postgresql_using=f"{toolcallstatus_column_name}::text::{toolcallstatus_enum_name}",
            existing_nullable=False,
        )

    toolcalltype_temp_type.drop(op.get_bind(), checkfirst=False)
    toolcallstatus_temp_type.drop(op.get_bind(), checkfirst=False)

    op.drop_constraint(
        "tool_calls_mcp_server_tool_id_fkey", "tool_calls", type_="foreignkey"
    )
    op.drop_column("tool_calls", "error")
    op.drop_column("tool_calls", "mcp_output")
    op.drop_column("tool_calls", "mcp_arguments")
    op.drop_column("tool_calls", "mcp_tool_name")
    op.drop_column("tool_calls", "mcp_server_tool_id")
    op.drop_column("tool_calls", "mcp_server_label")
    op.drop_table("mcp_list_tools_tools")
    op.drop_index(
        "mcp_server_tool_run_idx", table_name="mcp_server_tool_run_associations"
    )
    op.drop_table("mcp_server_tool_run_associations")
    op.drop_index(
        "mcp_server_tool_thread_idx", table_name="mcp_server_tool_thread_associations"
    )
    op.drop_table("mcp_server_tool_thread_associations")
    op.drop_index(
        "mcp_server_tool_assistant_idx",
        table_name="mcp_server_tool_assistant_associations",
    )
    op.drop_table("mcp_server_tool_assistant_associations")
    op.drop_index(
        op.f("ix_mcp_server_tools_server_label"), table_name="mcp_server_tools"
    )
    op.drop_table("mcp_server_tools")
    # ### end Alembic commands ###
