"""add columns for tracking files

Revision ID: 7bffc8dee7e3
Revises: 6095509a2761
Create Date: 2024-02-01 15:50:03.770426

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7bffc8dee7e3"
down_revision: Union[str, None] = "6095509a2761"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("uploader_id", sa.Integer(), nullable=True))
    op.add_column("files", sa.Column("private", sa.Boolean(), nullable=True))
    op.create_foreign_key(None, "files", "users", ["uploader_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "files", type_="foreignkey")
    op.drop_column("files", "private")
    op.drop_column("files", "uploader_id")
    # ### end Alembic commands ###
