"""Add Canvas API tokens

Revision ID: 7cb53b2d5f8f
Revises: 44edbf2cecbc
Create Date: 2024-07-24 15:16:28.800290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb53b2d5f8f'
down_revision: Union[str, None] = '44edbf2cecbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classes",
        sa.Column(
            "canvas_status",
            sa.Enum("NONE", "AUTHORIZED", "LINKED", "ERROR", "DISMISSED", name="canvasstatus"),
            nullable=True,
        ),
    )
    op.add_column('classes', sa.Column('canvas_user_name', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('canvas_course_id', sa.Integer(), nullable=True))
    op.add_column('classes', sa.Column('canvas_access_token', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('canvas_refresh_token', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('canvas_expires_in', sa.Integer(), nullable=True))
    op.add_column('classes', sa.Column('canvas_token_added_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'canvas_user_name')
    op.drop_column('classes', 'canvas_token_added_at')
    op.drop_column('classes', 'canvas_expires_in')
    op.drop_column('classes', 'canvas_refresh_token')
    op.drop_column('classes', 'canvas_access_token')
    op.drop_column('classes', 'canvas_course_id')
    op.drop_column('classes', 'canvas_status')
    # ### end Alembic commands ###
