"""Vision support

Revision ID: 7d6dde851734
Revises: 443687e4b64c
Create Date: 2024-06-20 21:28:58.332187

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d6dde851734"
down_revision: Union[str, None] = "443687e4b64c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_files_threads",
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("thread_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
    )
    op.create_index(
        "image_file_thread_idx",
        "image_files_threads",
        ["file_id", "thread_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_threads_assistant_id"), "threads", ["assistant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_threads_assistant_id"), table_name="threads")
    op.drop_index("image_file_thread_idx", table_name="image_files_threads")
    op.drop_table("image_files_threads")
    # ### end Alembic commands ###
