"""Hide Extra details

Revision ID: 838ea0f68a2e
Revises: bae099196767
Create Date: 2025-11-19 20:14:17.000681

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "838ea0f68a2e"
down_revision: Union[str, None] = "bae099196767"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistants",
        sa.Column(
            "hide_reasoning_summaries",
            sa.Boolean(),
            server_default="true",
            nullable=True,
        ),
    )
    op.add_column(
        "assistants",
        sa.Column(
            "hide_file_search_result_quotes",
            sa.Boolean(),
            server_default="true",
            nullable=True,
        ),
    )
    op.add_column(
        "assistants",
        sa.Column(
            "hide_file_search_document_names",
            sa.Boolean(),
            server_default="false",
            nullable=True,
        ),
    )
    op.add_column(
        "assistants",
        sa.Column(
            "hide_file_search_queries",
            sa.Boolean(),
            server_default="true",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "hide_file_search_result_quotes")
    op.drop_column("assistants", "hide_file_search_document_names")
    op.drop_column("assistants", "hide_file_search_queries")
    op.drop_column("assistants", "hide_reasoning_summaries")
    # ### end Alembic commands ###
