"""Add CanvasClass model

Revision ID: 842a791cb210
Revises: cc2533a20608
Create Date: 2024-08-01 14:57:22.961717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842a791cb210'
down_revision: Union[str, None] = 'cc2533a20608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvas_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canvas_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('course_code', sa.String(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canvas_id')
    )
    op.add_column('classes', sa.Column('canvas_class_id', sa.Integer(), nullable=True))
    op.create_foreign_key('classes_on_canvas_classes', 'classes', 'canvas_classes', ['canvas_class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('classes_on_canvas_classes', 'classes', type_='foreignkey')
    op.drop_column('classes', 'canvas_class_id')
    op.drop_table('canvas_classes')
    # ### end Alembic commands ###
