"""add_lecturevideo_table

Revision ID: 85b3ffaf5cfc
Revises: 867fefaae27b
Create Date: 2026-02-06 14:31:08.028373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b3ffaf5cfc'
down_revision: Union[str, None] = '867fefaae27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_lecture_videos_updated'), 'lecture_videos', ['updated'], unique=False)
    op.add_column('assistants', sa.Column('lecture_video_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_assistants_lecture_video_id_lecture_video', 'assistants', 'lecture_videos', ['lecture_video_id'], ['id'])
    op.add_column('lti_registrations', sa.Column('canvas_account_lti_guid', sa.String(), nullable=True))
    op.create_index('lti_canvas_account_lti_guid_idx', 'lti_registrations', ['canvas_account_lti_guid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('lti_canvas_account_lti_guid_idx', table_name='lti_registrations')
    op.drop_column('lti_registrations', 'canvas_account_lti_guid')
    op.drop_constraint('fk_assistants_lecture_video_id_lecture_video', 'assistants', type_='foreignkey')
    op.drop_column('assistants', 'lecture_video_id')
    op.drop_index(op.f('ix_lecture_videos_updated'), table_name='lecture_videos')
    op.drop_table('lecture_videos')
    # ### end Alembic commands ###
