"""add notes field to assistant

Revision ID: 867fefaae27b
Revises: a9eb133baba4
Create Date: 2026-01-21 15:47:41.207794

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "867fefaae27b"
down_revision: Union[str, None] = "a9eb133baba4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistants", sa.Column("notes", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "notes")
    # ### end Alembic commands ###
