"""Assistants: Add temperature column

Revision ID: 8c1d49d7fe53
Revises: d947e2748f31
Create Date: 2024-10-22 02:11:34.418011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1d49d7fe53'
down_revision: Union[str, None] = 'd947e2748f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('temperature', sa.Float(), server_default='1.0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'temperature')
    # ### end Alembic commands ###
