"""File-Class Remove Cascade

Revision ID: 8d98316591df
Revises: ef075fb14615
Create Date: 2025-06-02 02:13:38.107939

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8d98316591df"
down_revision: Union[str, None] = "ef075fb14615"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("files_class_id_fkey", "files", type_="foreignkey")
    op.create_foreign_key(
        "files_class_id_fkey", "files", "classes", ["class_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("files_class_id_fkey", "files", type_="foreignkey")
    op.create_foreign_key(
        "files_class_id_fkey",
        "files",
        "classes",
        ["class_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
