"""Thread Instructions Field

Revision ID: 8e32051ff46c
Revises: cdf1846c6866
Create Date: 2025-04-29 16:39:35.038927

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e32051ff46c"
down_revision: Union[str, None] = "cdf1846c6866"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("threads", sa.Column("instructions", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threads", "instructions")
    # ### end Alembic commands ###
