"""Threads: New user message count column and make name nullable

Revision ID: 8e800c07b278
Revises: eebdd27edf02
Create Date: 2024-10-01 14:23:55.320217

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e800c07b278"
down_revision: Union[str, None] = "eebdd27edf02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "threads",
        sa.Column("user_message_ct", sa.Integer(), server_default="1", nullable=True),
    )
    op.alter_column(
        "threads",
        "name",
        existing_type=sa.String(),
        nullable=True,
        server_default="New Conversation",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threads", "user_message_ct")
    op.alter_column(
        "threads",
        "name",
        existing_type=sa.String(),
        nullable=False,
        server_default=None,
    )
    # ### end Alembic commands ###
