"""Hide Extra Web Search details

Revision ID: 90e1564bb31d
Revises: 838ea0f68a2e
Create Date: 2025-11-24 14:17:28.920970

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90e1564bb31d"
down_revision: Union[str, None] = "838ea0f68a2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistants",
        sa.Column(
            "hide_web_search_sources",
            sa.Boolean(),
            server_default="false",
            nullable=True,
        ),
    )
    op.add_column(
        "assistants",
        sa.Column(
            "hide_web_search_actions",
            sa.Boolean(),
            server_default="false",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "hide_web_search_actions")
    op.drop_column("assistants", "hide_web_search_sources")
    # ### end Alembic commands ###
