"""Create separate code_interpreter file field

Revision ID: 942d1978ec88
Revises: 351f7fa9482e
Create Date: 2024-06-13 11:27:28.726342

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "942d1978ec88"
down_revision: Union[str, None] = "351f7fa9482e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "code_interpreter_files_assistants",
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("assistant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
    )
    op.create_index(
        "code_interpreter_file_assistant_idx",
        "code_interpreter_files_assistants",
        ["file_id", "assistant_id"],
        unique=True,
    )
    op.create_table(
        "code_interpreter_files_threads",
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("thread_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
    )
    op.create_index(
        "code_interpreter_file_thread_idx",
        "code_interpreter_files_threads",
        ["file_id", "thread_id"],
        unique=True,
    )
    op.drop_index("file_thread_idx", table_name="files_threads")
    op.drop_table("files_threads")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files_threads",
        sa.Column("file_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("thread_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name="files_threads_file_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["threads.id"], name="files_threads_thread_id_fkey"
        ),
    )
    op.create_index(
        "file_thread_idx", "files_threads", ["file_id", "thread_id"], unique=True
    )
    op.drop_index("file_thread_idx", table_name="code_interpreter_files_threads")
    op.drop_table("code_interpreter_files_threads")
    op.drop_index("file_assistant_idx", table_name="code_interpreter_files_assistants")
    op.drop_table("code_interpreter_files_assistants")
    # ### end Alembic commands ###
