"""Add WebSearch upgrades

Revision ID: 98c34815598b
Revises: 4452de1e99bc
Create Date: 2025-09-06 13:25:17.352144

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98c34815598b"
down_revision: Union[str, None] = "4452de1e99bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "web_search_call_search_sources", sa.Column("name", sa.String(), nullable=True)
    )
    op.alter_column(
        "web_search_call_search_sources",
        "url",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "web_search_call_search_sources",
        "url",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_column("web_search_call_search_sources", "name")
    # ### end Alembic commands ###
