"""Anonymous Links

Revision ID: 9953caba68c4
Revises: f1f48144ba41
Create Date: 2025-06-13 16:51:48.511085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9953caba68c4"
down_revision: Union[str, None] = "f1f48144ba41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anonymous_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("share_token", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("share_token"),
    )
    op.create_index(
        op.f("ix_anonymous_links_updated"), "anonymous_links", ["updated"], unique=False
    )
    op.create_table(
        "assistant_anonymous_links",
        sa.Column("assistant_id", sa.Integer(), nullable=True),
        sa.Column("link_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assistant_id"], ["assistants.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["link_id"], ["anonymous_links.id"], ondelete="CASCADE"
        ),
    )
    op.create_index(
        "assistant_link_idx",
        "assistant_anonymous_links",
        ["assistant_id", "link_id"],
        unique=True,
    )
    op.create_table(
        "anonymous_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_token", sa.String(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_token"),
    )
    op.add_column(
        "files", sa.Column("anonymous_session_id", sa.Integer(), nullable=True)
    )
    op.add_column("files", sa.Column("anonymous_link_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_files_anonymous_links",
        "files",
        "anonymous_links",
        ["anonymous_link_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_files_anonymous_sessions",
        "files",
        "anonymous_sessions",
        ["anonymous_session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("users", sa.Column("anonymous_link_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_users_anonymous_links",
        "users",
        "anonymous_links",
        ["anonymous_link_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_anonymous_links", "users", type_="foreignkey")
    op.drop_column("users", "anonymous_link_id")
    op.drop_constraint("fk_files_anonymous_links", "files", type_="foreignkey")
    op.drop_constraint("fk_files_anonymous_sessions", "files", type_="foreignkey")
    op.drop_column("files", "anonymous_link_id")
    op.drop_column("files", "anonymous_session_id")
    op.drop_table("anonymous_sessions")
    op.drop_index("assistant_link_idx", table_name="assistant_anonymous_links")
    op.drop_table("assistant_anonymous_links")
    op.drop_index(op.f("ix_anonymous_links_updated"), table_name="anonymous_links")
    op.drop_table("anonymous_links")
    # ### end Alembic commands ###
