"""Activity Summaries: last_summary_empty

Revision ID: a3f416db1eab
Revises: 392821b96cb0
Create Date: 2025-01-29 17:06:43.411521

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3f416db1eab"
down_revision: Union[str, None] = "392821b96cb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_classes",
        sa.Column(
            "last_summary_empty", sa.Boolean(), server_default="false", nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_classes", "last_summary_empty")
    # ### end Alembic commands ###
