"""Institution default api key

Revision ID: a54f5dd3ac9d
Revises: 90e1564bb31d
Create Date: 2025-12-18 18:25:35.255260

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a54f5dd3ac9d"
down_revision: Union[str, None] = "90e1564bb31d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "institutions", sa.Column("default_api_key_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "institutions_default_api_key_id_fkey",
        "institutions",
        "api_keys",
        ["default_api_key_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "institutions_default_api_key_id_fkey", "institutions", type_="foreignkey"
    )
    op.drop_column("institutions", "default_api_key_id")
    # ### end Alembic commands ###
