"""Add S3 Files

Revision ID: a805223f9983
Revises: bdeb2a584ac2
Create Date: 2025-08-02 15:43:46.767573

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a805223f9983"
down_revision: Union[str, None] = "bdeb2a584ac2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "s3_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_index(op.f("ix_s3_files_updated"), "s3_files", ["updated"], unique=False)
    op.add_column("files", sa.Column("s3_file_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_files_s3_files",
        "files",
        "s3_files",
        ["s3_file_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_files_s3_files", "files", type_="foreignkey")
    op.drop_column("files", "s3_file_id")
    op.drop_index(op.f("ix_s3_files_updated"), table_name="s3_files")
    op.drop_table("s3_files")
    # ### end Alembic commands ###
