"""Add canvas_account_lti_guid

Revision ID: a9eb133baba4
Revises: 371b3a44a211
Create Date: 2026-01-21 16:06:30.941423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a9eb133baba4"
down_revision: Union[str, None] = "371b3a44a211"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lti_registrations",
        sa.Column("canvas_account_lti_guid", sa.String(), nullable=True),
    )
    op.create_index(
        "lti_canvas_account_lti_guid_idx",
        "lti_registrations",
        ["canvas_account_lti_guid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("lti_canvas_account_lti_guid_idx", table_name="lti_registrations")
    op.drop_column("lti_registrations", "canvas_account_lti_guid")
    # ### end Alembic commands ###
