"""Assistants: Reasoning Effort

Revision ID: b26bb2fb8a1b
Revises: debb9c126ef6
Create Date: 2025-02-01 17:21:06.565374

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b26bb2fb8a1b"
down_revision: Union[str, None] = "debb9c126ef6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistants", sa.Column("reasoning_effort", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "assistants",
        "temperature",
        existing_type=sa.Float,
        nullable=True,
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "reasoning_effort")
    op.alter_column(
        "assistants",
        "temperature",
        existing_type=sa.Float,
        nullable=False,
        server_default="1.0",
    )
    # ### end Alembic commands ###
