"""Add allow_user_file_uploads to Assistant model

Revision ID: bae099196767
Revises: a0e423503265
Create Date: 2025-10-28 17:16:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bae099196767"
down_revision: Union[str, None] = "a0e423503265"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistants",
        sa.Column("allow_user_file_uploads", sa.Boolean(), server_default="true", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "allow_user_file_uploads")
    # ### end Alembic commands ###
