"""Add allow_user_file_uploads to Assistant model

Revision ID: bae099196767
Revises: 98c34815598b
Create Date: 2025-10-28 17:16:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bae099196767"
down_revision: Union[str, None] = "98c34815598b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistants",
        sa.Column(
            "allow_user_file_uploads",
            sa.Boolean(),
            server_default="true",
            nullable=True,
        ),
    )
    op.add_column(
        "assistants",
        sa.Column(
            "allow_user_image_uploads",
            sa.Boolean(),
            server_default="true",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "allow_user_file_uploads")
    op.drop_column("assistants", "allow_user_image_uploads")
    # ### end Alembic commands ###
