"""Anonymous Conversation ID

Revision ID: bdeb2a584ac2
Revises: 9953caba68c4
Create Date: 2025-06-26 02:30:58.483695

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bdeb2a584ac2"
down_revision: Union[str, None] = "9953caba68c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("threads", sa.Column("conversation_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threads", "conversation_id")
    # ### end Alembic commands ###
