"""Add Canvas API tokens

Revision ID: cc2533a20608
Revises: 44edbf2cecbc
Create Date: 2024-07-25 14:00:05.729646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc2533a20608'
down_revision: Union[str, None] = '44edbf2cecbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    canvas_status = sa.Enum('NONE', 'AUTHORIZED', 'LINKED', 'DISMISSED', 'ERROR', name='canvasstatus')
    canvas_status.create(op.get_bind(), checkfirst=True)
    op.add_column('classes', sa.Column('canvas_status', canvas_status, nullable=True))
    op.add_column('classes', sa.Column('canvas_user_id', sa.Integer(), nullable=True))
    op.add_column('classes', sa.Column('canvas_course_id', sa.Integer(), nullable=True))
    op.add_column('classes', sa.Column('canvas_access_token', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('canvas_refresh_token', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('canvas_expires_in', sa.Integer(), nullable=True))
    op.add_column('classes', sa.Column('canvas_token_added_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('classes', sa.Column('canvas_last_synced', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('classes_canvas_user_id_fkey', 'classes', 'users', ['canvas_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('classes_canvas_user_id_fkey', 'classes', type_='foreignkey')
    op.drop_column('classes', 'canvas_last_synced')
    op.drop_column('classes', 'canvas_token_added_at')
    op.drop_column('classes', 'canvas_expires_in')
    op.drop_column('classes', 'canvas_refresh_token')
    op.drop_column('classes', 'canvas_access_token')
    op.drop_column('classes', 'canvas_course_id')
    op.drop_column('classes', 'canvas_user_id')
    op.drop_column('classes', 'canvas_status')
    sa.Enum(name="canvasstatus").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
