"""Added Lecture Video case in the Interaction Mode Enum

Revision ID: d4843142e8de
Revises: 700e871f0775
Create Date: 2026-02-06 15:05:33.549155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4843142e8de"
down_revision: Union[str, None] = "700e871f0775"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


enum_name = "interactionmode"
temp_enum_name = f"temp_{enum_name}"
old_values = ("CHAT", "VOICE")
new_values = (*old_values, "LECTURE_VIDEO")
old_type = sa.Enum(*old_values, name=enum_name)
new_type = sa.Enum(*new_values, name=enum_name)
temp_type = sa.Enum(*new_values, name=temp_enum_name)

column_name = "interaction_mode"

assistants_table = "assistants"
assistants_simplified = sa.sql.table(
    assistants_table, sa.Column(column_name, new_type, nullable=False)
)

threads_table = "threads"
threads_simplified = sa.sql.table(
    threads_table, sa.Column(column_name, new_type, nullable=False)
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop server defaults before type change
    op.execute(
        f"ALTER TABLE {assistants_table} ALTER COLUMN {column_name} DROP DEFAULT"
    )
    op.execute(f"ALTER TABLE {threads_table} ALTER COLUMN {column_name} DROP DEFAULT")

    temp_type.create(op.get_bind(), checkfirst=False)

    with op.batch_alter_table(assistants_table) as batch_op:
        batch_op.alter_column(
            column_name,
            existing_type=old_type,
            type_=temp_type,
            postgresql_using=f"{column_name}::text::{temp_enum_name}",
            existing_nullable=False,
        )

    with op.batch_alter_table(threads_table) as batch_op:
        batch_op.alter_column(
            column_name,
            existing_type=old_type,
            type_=temp_type,
            postgresql_using=f"{column_name}::text::{temp_enum_name}",
            existing_nullable=False,
        )

    old_type.drop(op.get_bind(), checkfirst=False)
    new_type.create(op.get_bind(), checkfirst=False)

    with op.batch_alter_table(assistants_table) as batch_op:
        batch_op.alter_column(
            column_name,
            existing_type=temp_type,
            type_=new_type,
            postgresql_using=f"{column_name}::text::{enum_name}",
            existing_nullable=False,
        )

    with op.batch_alter_table(threads_table) as batch_op:
        batch_op.alter_column(
            column_name,
            existing_type=temp_type,
            type_=new_type,
            postgresql_using=f"{column_name}::text::{enum_name}",
            existing_nullable=False,
        )

    temp_type.drop(op.get_bind(), checkfirst=False)

    # Re-add server defaults
    op.execute(
        f"ALTER TABLE {assistants_table} ALTER COLUMN {column_name} SET DEFAULT 'CHAT'::{enum_name}"
    )
    op.execute(
        f"ALTER TABLE {threads_table} ALTER COLUMN {column_name} SET DEFAULT 'CHAT'::{enum_name}"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove rows with the new enum value to avoid issues during downgrade
    op.execute(
        threads_simplified.delete().where(
            threads_simplified.c.interaction_mode == "LECTURE_VIDEO"
        )
    )
    op.execute(
        assistants_simplified.delete().where(
            assistants_simplified.c.interaction_mode == "LECTURE_VIDEO"
        )
    )

    # Drop server defaults before type change
    op.execute(
        f"ALTER TABLE {assistants_table} ALTER COLUMN {column_name} DROP DEFAULT"
    )
    op.execute(f"ALTER TABLE {threads_table} ALTER COLUMN {column_name} DROP DEFAULT")

    temp_type.create(op.get_bind(), checkfirst=False)

    # Alter column types to temp enum
    with op.batch_alter_table(assistants_table) as batch_op:
        batch_op.alter_column(
            column_name,
            existing_type=new_type,
            type_=temp_type,
            postgresql_using=f"{column_name}::text::{temp_enum_name}",
            existing_nullable=False,
        )

    with op.batch_alter_table(threads_table) as batch_op:
        batch_op.alter_column(
            column_name,
            existing_type=new_type,
            type_=temp_type,
            postgresql_using=f"{column_name}::text::{temp_enum_name}",
            existing_nullable=False,
        )
    new_type.drop(op.get_bind(), checkfirst=False)
    old_type.create(op.get_bind(), checkfirst=False)

    # Alter column types to old enum
    with op.batch_alter_table(assistants_table) as batch_op:
        batch_op.alter_column(
            column_name,
            existing_type=temp_type,
            type_=old_type,
            postgresql_using=f"{column_name}::text::{enum_name}",
            existing_nullable=False,
        )

    with op.batch_alter_table(threads_table) as batch_op:
        batch_op.alter_column(
            column_name,
            existing_type=temp_type,
            type_=old_type,
            postgresql_using=f"{column_name}::text::{enum_name}",
            existing_nullable=False,
        )

    temp_type.drop(op.get_bind(), checkfirst=False)

    # Re-add server defaults
    op.execute(
        f"ALTER TABLE {assistants_table} ALTER COLUMN {column_name} SET DEFAULT 'CHAT'::{enum_name}"
    )
    op.execute(
        f"ALTER TABLE {threads_table} ALTER COLUMN {column_name} SET DEFAULT 'CHAT'::{enum_name}"
    )
    # ### end Alembic commands ###
