"""Thread Timezone Field

Revision ID: d4b0b2935042
Revises: 8e32051ff46c
Create Date: 2025-04-29 22:51:59.128091

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4b0b2935042"
down_revision: Union[str, None] = "8e32051ff46c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("threads", sa.Column("timezone", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threads", "timezone")
    # ### end Alembic commands ###
