"""Classes: Add last rate limited timestamp

Revision ID: d947e2748f31
Revises: 8e800c07b278
Create Date: 2024-10-11 15:42:24.609928

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d947e2748f31"
down_revision: Union[str, None] = "8e800c07b278"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classes",
        sa.Column("last_rate_limited_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classes", "last_rate_limited_at")
    # ### end Alembic commands ###
