"""Add verbosity

Revision ID: dc52d12c16db
Revises: 2b8a809f389b
Create Date: 2025-09-05 14:33:38.161705

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc52d12c16db"
down_revision: Union[str, None] = "2b8a809f389b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistants", sa.Column("verbosity", sa.Integer(), nullable=True))
    op.add_column("runs", sa.Column("verbosity", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "verbosity")
    op.drop_column("runs", "verbosity")
    # ### end Alembic commands ###
