"""Assistants: Use Image Descriptions

Revision ID: dcf2fe04f74f
Revises: b26bb2fb8a1b
Create Date: 2025-02-11 01:26:47.764351

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dcf2fe04f74f"
down_revision: Union[str, None] = "b26bb2fb8a1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistants", sa.Column("use_image_descriptions", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "use_image_descriptions")
    # ### end Alembic commands ###
