"""External Logins: New ExternalLoginProvider table

Revision ID: debb9c126ef6
Revises: e7eab514d4a9
Create Date: 2025-01-31 13:18:55.666781

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "debb9c126ef6"
down_revision: Union[str, None] = "e7eab514d4a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_login_providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "external_logins", sa.Column("provider_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        "idx_user_provider_id",
        "external_logins",
        ["user_id", "provider_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_user_provider_id_identifier",
        "external_logins",
        ["user_id", "provider_id", "identifier"],
    )
    op.create_foreign_key(
        "external_login_prov_fk",
        "external_logins",
        "external_login_providers",
        ["provider_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("external_login_prov_fk", "external_logins", type_="foreignkey")
    op.drop_constraint(
        "uq_user_provider_id_identifier", "external_logins", type_="unique"
    )
    op.drop_index("idx_user_provider_id", table_name="external_logins")
    op.drop_column("external_logins", "provider_id")
    op.drop_table("external_login_providers")
    # ### end Alembic commands ###
