"""Add API Key table

Revision ID: dfd24880d2ac
Revises: 8c1d49d7fe53
Create Date: 2024-11-22 11:15:33.396414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dfd24880d2ac"
down_revision: Union[str, None] = "8c1d49d7fe53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=True),
        sa.Column("api_version", sa.String(), nullable=True),
        sa.Column("available_as_default", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key", "provider", name="_key_provider_uc"),
    )
    op.create_index(
        "api_key_available_as_default_idx",
        "api_keys",
        ["available_as_default"],
        unique=False,
    )
    op.add_column("classes", sa.Column("api_key_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "_classes_api_keys_fk", "classes", "api_keys", ["api_key_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_classes_api_keys_fk", "classes", type_="foreignkey")
    op.drop_column("classes", "api_key_id")
    op.drop_index("api_key_available_as_default_idx", table_name="api_keys")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
