"""Add API Key name

Revision ID: e2e5ea5b9e4c
Revises: ab0efa9c4c78
Create Date: 2024-11-21 19:43:48.310429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e5ea5b9e4c'
down_revision: Union[str, None] = 'ab0efa9c4c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'name')
    # ### end Alembic commands ###
