"""Add Canvas notation in UserRoles

Revision ID: e3627728e6b0
Revises: 842a791cb210
Create Date: 2024-08-01 16:47:11.432275

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3627728e6b0"
down_revision: Union[str, None] = "842a791cb210"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_classes", sa.Column("from_canvas", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_classes", "from_canvas")
    # ### end Alembic commands ###
