"""Add SSO Merging dependencies

Revision ID: e5c0c20c37a9
Revises: 5acfd7c7485f
Create Date: 2024-09-06 18:39:32.133710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c0c20c37a9'
down_revision: Union[str, None] = '5acfd7c7485f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_logins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='_user_provider_uc')
    )
    op.create_unique_constraint('_user_class_uc', 'users_classes', ['user_id', 'class_id'])
    op.drop_column('users_classes', 'sso_tenant')
    op.drop_column('users_classes', 'sso_id')
    op.create_unique_constraint('_user_inst_uc', 'users_institutions', ['user_id', 'institution_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_inst_uc', 'users_institutions', type_='unique')
    op.add_column('users_classes', sa.Column('sso_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users_classes', sa.Column('sso_tenant', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('_user_class_uc', 'users_classes', type_='unique')
    op.drop_table('external_logins')
    # ### end Alembic commands ###
