"""Activity Summaries: DNAs

Revision ID: e7eab514d4a9
Revises: a3f416db1eab
Create Date: 2025-01-29 18:20:24.844314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7eab514d4a9'
down_revision: Union[str, None] = 'a3f416db1eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dna_as_join', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('users', sa.Column('dna_as_create', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dna_as_create')
    op.drop_column('users', 'dna_as_join')
    # ### end Alembic commands ###
