"""Add LTI

Revision ID: e920bdf08505
Revises: a54f5dd3ac9d
Create Date: 2025-12-18 16:29:36.471794

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e920bdf08505"
down_revision: Union[str, None] = "a54f5dd3ac9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lti_registrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("issuer", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=True),
        sa.Column("auth_login_url", sa.String(), nullable=False),
        sa.Column("auth_token_url", sa.String(), nullable=False),
        sa.Column("key_set_url", sa.String(), nullable=False),
        sa.Column(
            "token_algorithm",
            sa.Enum("RS256", name="ltitokenalgorithm"),
            nullable=False,
        ),
        sa.Column("lms_platform", sa.Enum("CANVAS", name="lmsplatform"), nullable=True),
        sa.Column("canvas_account_name", sa.String(), nullable=True),
        sa.Column("configuration", sa.String(), nullable=True),
        sa.Column("admin_name", sa.String(), nullable=True),
        sa.Column("admin_email", sa.String(), nullable=True),
        sa.Column("friendly_name", sa.String(), nullable=True),
        sa.Column(
            "review_status",
            sa.Enum(
                "PENDING", "APPROVED", "REJECTED", name="ltiregistrationreviewstatus"
            ),
            server_default="PENDING",
            nullable=True,
        ),
        sa.Column("review_notes", sa.String(), nullable=True),
        sa.Column("public_notes", sa.String(), nullable=True),
        sa.Column("review_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["review_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lti_registrations")
    sa.Enum("CANVAS", name="lmsplatform").drop(op.get_bind(), checkfirst=True)
    sa.Enum("PENDING", "APPROVED", "REJECTED", name="ltiregistrationreviewstatus").drop(
        op.get_bind(), checkfirst=True
    )
    sa.Enum("RS256", name="ltitokenalgorithm").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
