"""Threads: Auto-Cascade

Revision ID: eebdd27edf02
Revises: f6b732d2f120
Create Date: 2024-09-26 17:46:16.218236

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "eebdd27edf02"
down_revision: Union[str, None] = "f6b732d2f120"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "code_interpreter_files_threads_file_id_fkey",
        "code_interpreter_files_threads",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "code_interpreter_files_threads_file_id_fkey",
        "code_interpreter_files_threads",
        "files",
        ["file_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "file_vector_stores_file_id_fkey", "file_vector_stores", type_="foreignkey"
    )
    op.create_foreign_key(
        "file_vector_stores_file_id_fkey",
        "file_vector_stores",
        "files",
        ["file_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "file_vector_stores_file_id_fkey", "file_vector_stores", type_="foreignkey"
    )
    op.create_foreign_key(
        "file_vector_stores_file_id_fkey",
        "file_vector_stores",
        "files",
        ["file_id"],
        ["id"],
    )
    op.drop_constraint(
        "code_interpreter_files_threads_file_id_fkey",
        "code_interpreter_files_threads",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "code_interpreter_files_threads_file_id_fkey",
        "code_interpreter_files_threads",
        "files",
        ["file_id"],
        ["id"],
    )
    # ### end Alembic commands ###
