"""File-Class Association

Revision ID: ef075fb14615
Revises: d4b0b2935042
Create Date: 2025-06-01 18:48:23.395897

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef075fb14615"
down_revision: Union[str, None] = "d4b0b2935042"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_classes",
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("class_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["class_id"], ["classes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
    )
    op.create_index(
        "file_class_idx", "file_classes", ["file_id", "class_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("file_class_idx", table_name="file_classes")
    op.drop_table("file_classes")
    # ### end Alembic commands ###
