"""add column for assistant description

Revision ID: ef79c15112d7
Revises: 22ef0e00b450
Create Date: 2024-01-18 16:15:54.613637

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef79c15112d7"
down_revision: Union[str, None] = "22ef0e00b450"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistants", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "description")
    # ### end Alembic commands ###
