"""add columns for more class permissions

Revision ID: effcaa8bbcd2
Revises: 7bffc8dee7e3
Create Date: 2024-03-29 14:53:49.092682

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "effcaa8bbcd2"
down_revision: Union[str, None] = "7bffc8dee7e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classes", sa.Column("any_can_publish_thread", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "classes", sa.Column("any_can_upload_class_file", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classes", "any_can_upload_class_file")
    op.drop_column("classes", "any_can_publish_thread")
    # ### end Alembic commands ###
