"""Voice Mode Recordings

Revision ID: f1f48144ba41
Revises: 8d98316591df
Create Date: 2025-06-08 11:40:06.433991

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1f48144ba41"
down_revision: Union[str, None] = "8d98316591df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voice_mode_recordings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=True),
        sa.Column("recording_id", sa.String(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recording_id"),
    )
    op.add_column(
        "assistants",
        sa.Column(
            "should_record_user_information",
            sa.Boolean(),
            server_default="false",
            nullable=True,
        ),
    )
    op.add_column(
        "threads",
        sa.Column(
            "display_user_info", sa.Boolean(), server_default="false", nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threads", "display_user_info")
    op.drop_column("assistants", "should_record_user_information")
    op.drop_table("voice_mode_recordings")
    # ### end Alembic commands ###
