"""Threads: Add last_activity column

Revision ID: f6b732d2f120
Revises: 4b6d8576721d
Create Date: 2024-09-19 12:52:53.553478

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6b732d2f120"
down_revision: Union[str, None] = "4b6d8576721d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("threads", sa.Column("last_activity", sa.DateTime(timezone=True)))
    op.execute("""
        UPDATE threads
        SET last_activity = updated, updated = updated
    """)
    op.alter_column("threads", "last_activity", nullable=False)
    op.create_index(
        op.f("ix_threads_last_activity"), "threads", ["last_activity"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_threads_last_activity"), table_name="threads")
    op.drop_column("threads", "last_activity")
    # ### end Alembic commands ###
