"""Add internal_only in ExternalLoginProvider

Revision ID: f9f8097f7ce1
Revises: c8d5340377ab
Create Date: 2026-02-09 21:11:25.253590

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f9f8097f7ce1"
down_revision: Union[str, None] = "c8d5340377ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Resolves CodeQL's py/unused-global-variable
    _ = revision, down_revision, branch_labels, depends_on
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "external_login_providers",
        sa.Column(
            "internal_only", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("external_login_providers", "internal_only")
    # ### end Alembic commands ###
