from typing import Final


DEFAULT_ELEVENLABS_STABILITY: Final = 0.5
DEFAULT_ELEVENLABS_USE_SPEAKER_BOOST: Final = True
DEFAULT_ELEVENLABS_SIMILARITY_BOOST: Final = 0.8
DEFAULT_ELEVENLABS_STYLE: Final = 0.0
DEFAULT_ELEVENLABS_SPEED: Final = 1.0
